# -*- coding: utf-8 -*-

generalPathTest: "/product_data/data/pay/Kenya/MKN/incoming/test_structure/"
sourceTest: "~/My Documents/Praktikum/git/file_directory/Test_data.csv"

generalPathMKN: "/product_data/data/pay/Kenya/MKN/incoming/"
sourceMKN: "~/My Documents/Praktikum/git/file_directory/MKN_data.csv"

generalPathNRB: "/product_data/data/pay/Kenya/NRB/"
sourceNRB: "~/My Documents/Praktikum/git/file_directory/NRB_data.csv"
