# -*- coding: utf-8 -*-



generalPathMKN: "/home/sdanioth/Documents/Test_data/Kenya/MKN/incoming/"
sourceMKN: "/home/sdanioth/Documents/git/file_directory/file_directory/MKN_data.csv"

generalPathNRB: "/home/sdanioth/Documents/Test_data/Kenya/NRB/"
sourceNRB: "/home/sdanioth/Documents/git/file_directory/file_directory/NRB_data.csv"
